version: '2'
services:
  ats:
    image: quay.io/7insyde/ats
    container_name: ats
    ports:
      - "8080:8080"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    networks:
      - 7insyde
networks:
  7insyde:
    external: true